routes/web.php
<?php
use Illuminate\Support\Facades\Mail;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
})->name('site');

Route::get('/sobre', function () {
	return view('about');
})->name('about');

Route::get('/servicos', function () {
	return view('services');
})->name('services');

Auth::routes();

Route::put('/email', 'EmailController@store')->name('email');
Route::get('/fale-conosco', 'EmailController@create')->name('contact');
// Auth Routes
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login');
Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::get('/sistema/', 'HomeController@index')->name('home');
Route::get('/cadastro', 'Auth\RegisterController@showPerfil')->name('register');
Route::get('/cadastro/veterinario', 'Auth\ClinicController@showVeterinario')->name('vet');
Route::post('/cadastro/veterinario', 'Auth\ClinicController@store')->name('RegisterVet');
Route::get('/cadastro/ongs', 'Auth\OngController@showOngs')->name('ongs');
Route::get('/ongs', 'OngController@index')->name('ongscadastradas');
Route::get('/ongs/{id}/{name}', 'OngController@show')->name('ongs.show');
Route::post('/cadastro/ongs', 'Auth\OngController@store')->name('RegisterOngs');
Route::get('/cadastro/usuario', 'Auth\RegisterController@showUsuario')->name('fisico');
Route::post('/cadastro', 'Auth\RegisterController@store')->name('register');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/senha/alterar-senha', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::get('/confirmacao/{email?}', 'confirmationController@confirmacao')->name('public.confirm');

Route::group(['middleware' => 'auth'], function () {
	
	
	Route::post('/sistema/chat', 'ChatController@index')->name('chat');
	Route::post('/sistema/mensagem', 'ChatController@show')->name('conversa');
	Route::post('/sistema/chat/enviar', 'ChatController@enviamensagem')->name('mensagem');
	Route::resource('/sistema/usuario', 'UserController', ['except' => ['show']]);
	Route::resource('/sistema/animal', 'AnimalController', ['except' => ['show']]);
	Route::get('/sistema/perfil', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::get('/sistema/animal/view/{id}/{name}', 'AnimalController@show')->name('animal.show');
	Route::get('/sistema/contrato/{id}/{name}', 'PdfviewController@index')->name('contrato');
	Route::get('/sistema/animal/adicionar', ['as' => 'animal.adicionar', 'uses' => 'AnimalController@create']);
	Route::put('/sistema/perfil', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('/sistema/perfil/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('/sistema/adocao/search', ['as' => 'adopter.search', 'uses' => 'AdoptionController@search']);
	Route::get('/sistema/perdido/search', ['as' => 'lost.search', 'uses' => 'LostController@search']);
	Route::get('/sistema/animal/search', ['as' => 'animal.search', 'uses' => 'AnimalController@search']);
	Route::get('/sistema/animal/pesquisa', ['as' => 'animal.pesquisa', 'uses' => 'AnimalController@pesquisa']);
	Route::put('/sistema/perfil/veterinario', ['as' => 'profile.veterinario', 'uses' => 'ProfileController@updateClinic']);
	
	Route::get('/sistema/dono/{id}', 'AnimalController@dono')->name('emaildono');
	Route::put('/sistema/animal/perdido/{id}', 'LostController@localization')->name('lost.addresses');

	Route::put('/sistema/perfil/employee', ['as' => 'profile.employee', 'uses' => 'ProfileController@updateEmployee']);
	Route::put('/sistema/perfil/ong', ['as' => 'profile.ong', 'uses' => 'ProfileController@updateong']);
	Route::put('/sistema/perfil/socialnetworks', ['as' => 'profile.social', 'uses' => 'ProfileController@updateSocial']);

	Route::get('/sistema/perdidos', ['as' => 'perdidos', 'uses' => 'LostController@index']);
	Route::get('/sistema/perdidos/cachorros', ['as' => 'perdidos.dog', 'uses' => 'LostController@dog']);
	Route::get('/sistema/perdidos/furoes', ['as' => 'perdidos.furao', 'uses' => 'LostController@furao']);
	Route::get('/sistema/perdidos/gatos', ['as' => 'perdidos.cat', 'uses' => 'LostController@cat']);
	Route::get('/sistema/perdidos/roedores', ['as' => 'perdidos.rodents', 'uses' => 'LostController@rodents']);
	Route::get('/sistema/perdidos/coelhos', ['as' => 'perdidos.rabbits', 'uses' => 'LostController@rabbits']);
	Route::get('/sistema/perdidos/aves', ['as' => 'perdidos.birds', 'uses' => 'LostController@birds']);
	Route::get('/sistema/perdidos/tartarugas-jabutis-e-cagados', ['as' => 'perdidos.turtles', 'uses' => 'LostController@turtles']);

	Route::get('/sistema/adocao', ['as' => 'adocao', 'uses' => 'AdoptionController@index']);
	Route::get('/sistema/adocao/cachorros', ['as' => 'adocao.dog', 'uses' => 'AdoptionController@dog']);
	Route::get('/sistema/adocao/furoes', ['as' => 'adocao.furao', 'uses' => 'AdoptionController@furao']);
	Route::get('/sistema/adocao/gatos', ['as' => 'adocao.cat', 'uses' => 'AdoptionController@cat']);
	Route::get('/sistema/adocao/roedores', ['as' => 'adocao.rodents', 'uses' => 'AdoptionController@rodents']);
	Route::get('/sistema/adocao/coelhos', ['as' => 'adocao.rabbits', 'uses' => 'AdoptionController@rabbits']);
	Route::get('/sistema/adocao/aves', ['as' => 'adocao.birds', 'uses' => 'AdoptionController@birds']);
	Route::get('/sistema/adocao/tartarugas-jabutis-e-cagados', ['as' => 'adocao.turtles', 'uses' => 'AdoptionController@turtles']);

	Route::put('/sistema/perfil/avatar', ['as' => 'profile.updateAvatar', 'uses' => 'ProfileController@updateAvatar']);

	Route::resource('/sistema/state', 'StateController', ['except' => ['show']]);
	Route::resource('/sistema/city', 'CityController', ['except' => ['show']]);

	Route::resource('/sistema/usuario', 'UserController', ['except' => ['show']]);
	Route::resource('/sistema/empregado', 'EmployeeController', ['except' => ['show']]);
	Route::get('/sistema/empregado/adicionar', ['as' => 'employee.adicionar', 'uses' => 'EmployeeController@create']);
});

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use App\Models\User;
use App\Models\Ong;
use App\Http\Requests\EmployeeRequest;
use Illuminate\Support\Facades\Mail;
use App\Models\Clinic;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        if(auth()->user()->role=="ong"){
            $ong = Ong::where('user_id', '=', auth()->user()->id)->get();

            $users = User::orderby('users.name', 'asc')->join('ong_user', 'ong_user.user_id', '=', 'users.id')->where('ong_user.ong_id', '=', $ong[0]->id)->paginate(15);
        }else{
            $clinic = Clinic::where('user_id', '=', auth()->user()->id)->get();
            
            $users = User::orderby('users.name', 'asc')->join('clinic_user', 'clinic_user.user_id', '=', 'users.id')->where('clinic_user.clinic_id', '=', $clinic[0]->id)->paginate(15);
        }
        return view('employee.users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employee.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
    public function store(EmployeeRequest $request)
    {
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = 'employee';
        $user->password = Hash::make($request->password);
        $user->save();

        if(auth()->user()->role == "ong"){
            $ong = Ong::where('user_id', '=', auth()->user()->id)->get();
            $name = $ong[0]->name;
            $user->ongs()->sync([$ong[0]->id]);
        }else{

            $clinic = Clinic::where('user_id', '=', auth()->user()->id)->get();
            $name = $clinic[0]->name;
            $user->clinics()->sync([$clinic[0]->id]);
        }
        Mail::send(new \App\Mail\ConfirmationUser($request));

        return redirect()->route('empregado.index')->withStatus(__('Usuario adicionado com Sucesso.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $data = [
            "user" => $user
        ];
        return view('employee.users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();

        return redirect()->route('empregado.index')->withStatus(__('Usuario Editado com Sucesso.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function destroy(Request $request)
    {
        $user = User::find($request->id);
        $user->delete();
        return redirect()->route('empregado.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {

        if(auth()->user()->role == "admin")
            $view = view("admin.users.index", ['users' => $model->where('role', '<>', 'employee')->paginate(15)]);
        else  
            $view = redirect()->route('home');
        return $view;
    }

    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        
        if(auth()->user()->role == "admin")
            $view = view("admin.users.create");
        else  
            $view = redirect()->route('home');
        return $view;
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, User $model)
    {
        $model->name = $request->name;
        $model->email = $request->email;
        $model->role = $request->role;
        $model->password = Hash::make($request->password);
        $model->save();

        return redirect()->route('usuario.index')->withStatus(__('Usuario criado com Sucesso.'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::find($id);
        if(auth()->user()->role == "admin")
            $view = view("admin.users.edit", compact('user'));
        else  
            $view = redirect()->route('home');
        return $view;
    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $model = User::find($id);
        $model->name = $request->name;
        $model->email = $request->email;
        $model->role = $request->role;
        $model->password = Hash::make($request->password);
        $model->save();

        return redirect()->route('usuario.index')->withStatus(__('Usuario atualizado com Sucesso.'));
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if($user->role=="vet"){
            $clinica=$user->clinicsUsuario;
            if(sizeof($clinica->users)>0){
                foreach($clinica->users as $usuarios){
                    $usuarios->delete();
                }
            }
            $clinica->delete();
        }else if($user->role=="ong"){
            $ong=$user->ongsUsuario;
            if(sizeof($ong->users)>0){
                foreach($ong->users as $usuarios){
                    $usuarios->delete();
                }
            }
            $ong->delete();
        }
        $user->delete();

        return redirect()->route('usuario.index')->withStatus(__('Usuario Deletado com sucesso.'));
    }
}

resources/views/employee/users/create.blade.php
@extends('layouts.app', ['title' => __('Adicionar Empregado')])

@section('content')
@include('profile.partials.header', [
'title' => __('Novo Empregado'),
'class' => 'col-lg-12'
])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h3 class="mb-3">{{ __('Novo Usuario') }}</h3>
                            </div>
                            <div class="col-md-4 mb-3 text-right">
                                <a href="{{ route('empregado.index') }}" class="btn btn-sm btn-primary">{{ __('Voltar para a lista') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('empregado.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-white mb-4">{{ __('Informações do usuario') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nome') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nome') }}" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-password">{{ __('Senha') }}</label>
                                    <input type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Insira uma senha') }}" value="" required>
                                    
                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-password-confirmation">{{ __('Confirme a Senha') }}</label>
                                    <input type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirme a Senha aqui') }}" value="" required>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary mt-4">{{ __('Salvar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/employee/users/edit.blade.php
@extends('layouts.app', ['title' => __('Editar Empregado')])

@section('content')
@include('profile.partials.header', [
'title' => __('Editar Empregado'),
'class' => 'col-lg-12'
])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Edição de Empregado') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('empregado.index') }}" class="btn btn-sm btn-primary">{{ __('Voltar para a lista') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('empregado.update', $user) }}" autocomplete="off">
                            @csrf
                            @method('put')

                            <h6 class="heading-small text-white mb-4">{{ __('Informação do Usuario') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nome') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nome') }}" value="{{ old('name', $user->name) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email', $user->email) }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-password">{{ __('Senha') }}</label>
                                    <input type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Senha') }}" value="">
                                    
                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-password-confirmation">{{ __('Confirme a Senha') }}</label>
                                    <input type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirme a Senha') }}" value="">
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary mt-4">{{ __('Salvar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/employee/users/index.blade.php
@extends('layouts.app', ['title' => __('Empregados')])

@section('content')
@include('profile.partials.header', [
'title' => __('Seus Empregados'),
'class' => 'col-lg-12'
])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Usuarios') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('employee.adicionar') }}" class="btn btn-sm btn-primary">{{ __('Adicionar Usuario') }}</a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Nome') }}</th>
                                    <th scope="col">{{ __('Email') }}</th>
                                    <th scope="col">{{ __('Data de Criação') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td>{{ $user->name }}</td>
                                        <td>
                                            <a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
                                        </td>
                                        <td>{{ $user->created_at->format('d/m/Y H:i') }}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    @if ($user->id != auth()->id())
                                                        <form action="{{ route('empregado.destroy', $user->id) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            <input type="hidden" name="id" value="{{ $user->id }}">
                                                            <a class="dropdown-item" href="{{ route('empregado.edit', $user) }}">{{ __('Edit') }}</a>
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __("Você tem certeza que quer deletar esse usuario?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Delete') }}
                                                            </button>
                                                        </form>    
                                                    @else
                                                        <a class="dropdown-item" href="{{ route('profile.edit') }}">{{ __('Edit') }}</a>
                                                    @endif
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $users->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection