routes/web.php
<?php
use Illuminate\Support\Facades\Mail;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
})->name('site');

Route::get('/sobre', function () {
	return view('about');
})->name('about');

Route::get('/servicos', function () {
	return view('services');
})->name('services');

Auth::routes();

Route::put('/email', 'EmailController@store')->name('email');
Route::get('/fale-conosco', 'EmailController@create')->name('contact');
// Auth Routes
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login');
Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::get('/sistema/', 'HomeController@index')->name('home');
Route::get('/cadastro', 'Auth\RegisterController@showPerfil')->name('register');
Route::get('/cadastro/veterinario', 'Auth\ClinicController@showVeterinario')->name('vet');
Route::post('/cadastro/veterinario', 'Auth\ClinicController@store')->name('RegisterVet');
Route::get('/cadastro/ongs', 'Auth\OngController@showOngs')->name('ongs');
Route::get('/ongs', 'OngController@index')->name('ongscadastradas');
Route::get('/ongs/{id}/{name}', 'OngController@show')->name('ongs.show');
Route::post('/cadastro/ongs', 'Auth\OngController@store')->name('RegisterOngs');
Route::get('/cadastro/usuario', 'Auth\RegisterController@showUsuario')->name('fisico');
Route::post('/cadastro', 'Auth\RegisterController@store')->name('register');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/senha/alterar-senha', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::get('/confirmacao/{email?}', 'confirmationController@confirmacao')->name('public.confirm');

Route::group(['middleware' => 'auth'], function () {
	
	
	Route::post('/sistema/chat', 'ChatController@index')->name('chat');
	Route::post('/sistema/mensagem', 'ChatController@show')->name('conversa');
	Route::post('/sistema/chat/enviar', 'ChatController@enviamensagem')->name('mensagem');
	Route::resource('/sistema/usuario', 'UserController', ['except' => ['show']]);
	Route::resource('/sistema/animal', 'AnimalController', ['except' => ['show']]);
	Route::get('/sistema/perfil', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::get('/sistema/animal/view/{id}/{name}', 'AnimalController@show')->name('animal.show');
	Route::get('/sistema/contrato/{id}/{name}', 'PdfviewController@index')->name('contrato');
	Route::get('/sistema/animal/adicionar', ['as' => 'animal.adicionar', 'uses' => 'AnimalController@create']);
	Route::put('/sistema/perfil', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('/sistema/perfil/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('/sistema/adocao/search', ['as' => 'adopter.search', 'uses' => 'AdoptionController@search']);
	Route::get('/sistema/perdido/search', ['as' => 'lost.search', 'uses' => 'LostController@search']);
	Route::get('/sistema/animal/search', ['as' => 'animal.search', 'uses' => 'AnimalController@search']);
	Route::get('/sistema/animal/pesquisa', ['as' => 'animal.pesquisa', 'uses' => 'AnimalController@pesquisa']);
	Route::put('/sistema/perfil/veterinario', ['as' => 'profile.veterinario', 'uses' => 'ProfileController@updateClinic']);
	
	Route::get('/sistema/dono/{id}', 'AnimalController@dono')->name('emaildono');
	Route::put('/sistema/animal/perdido/{id}', 'LostController@localization')->name('lost.addresses');

	Route::put('/sistema/perfil/employee', ['as' => 'profile.employee', 'uses' => 'ProfileController@updateEmployee']);
	Route::put('/sistema/perfil/ong', ['as' => 'profile.ong', 'uses' => 'ProfileController@updateong']);
	Route::put('/sistema/perfil/socialnetworks', ['as' => 'profile.social', 'uses' => 'ProfileController@updateSocial']);

	Route::get('/sistema/perdidos', ['as' => 'perdidos', 'uses' => 'LostController@index']);
	Route::get('/sistema/perdidos/cachorros', ['as' => 'perdidos.dog', 'uses' => 'LostController@dog']);
	Route::get('/sistema/perdidos/furoes', ['as' => 'perdidos.furao', 'uses' => 'LostController@furao']);
	Route::get('/sistema/perdidos/gatos', ['as' => 'perdidos.cat', 'uses' => 'LostController@cat']);
	Route::get('/sistema/perdidos/roedores', ['as' => 'perdidos.rodents', 'uses' => 'LostController@rodents']);
	Route::get('/sistema/perdidos/coelhos', ['as' => 'perdidos.rabbits', 'uses' => 'LostController@rabbits']);
	Route::get('/sistema/perdidos/aves', ['as' => 'perdidos.birds', 'uses' => 'LostController@birds']);
	Route::get('/sistema/perdidos/tartarugas-jabutis-e-cagados', ['as' => 'perdidos.turtles', 'uses' => 'LostController@turtles']);

	Route::get('/sistema/adocao', ['as' => 'adocao', 'uses' => 'AdoptionController@index']);
	Route::get('/sistema/adocao/cachorros', ['as' => 'adocao.dog', 'uses' => 'AdoptionController@dog']);
	Route::get('/sistema/adocao/furoes', ['as' => 'adocao.furao', 'uses' => 'AdoptionController@furao']);
	Route::get('/sistema/adocao/gatos', ['as' => 'adocao.cat', 'uses' => 'AdoptionController@cat']);
	Route::get('/sistema/adocao/roedores', ['as' => 'adocao.rodents', 'uses' => 'AdoptionController@rodents']);
	Route::get('/sistema/adocao/coelhos', ['as' => 'adocao.rabbits', 'uses' => 'AdoptionController@rabbits']);
	Route::get('/sistema/adocao/aves', ['as' => 'adocao.birds', 'uses' => 'AdoptionController@birds']);
	Route::get('/sistema/adocao/tartarugas-jabutis-e-cagados', ['as' => 'adocao.turtles', 'uses' => 'AdoptionController@turtles']);

	Route::put('/sistema/perfil/avatar', ['as' => 'profile.updateAvatar', 'uses' => 'ProfileController@updateAvatar']);

	Route::resource('/sistema/state', 'StateController', ['except' => ['show']]);
	Route::resource('/sistema/city', 'CityController', ['except' => ['show']]);

	Route::resource('/sistema/usuario', 'UserController', ['except' => ['show']]);
	Route::resource('/sistema/empregado', 'EmployeeController', ['except' => ['show']]);
	Route::get('/sistema/empregado/adicionar', ['as' => 'employee.adicionar', 'uses' => 'EmployeeController@create']);
});

app/Models/Animal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Animal extends Model
{
	public function types(){
		return $this->belongsTo('App\Models\Type', 'type_id');
	}
	public function breeds(){
		return $this->belongsTo('App\Models\Breed', "breed_id");
	}

	public function adoption(){
		return $this->hasOne("App\Models\Adoption");
	}
	public function lost(){
		return $this->hasOne("App\Models\Lost");
	}
	public function logo()
	{
		return $this->morphOne('App\Models\Logo', 'imageable')->where('type','logo');
	}

	public function avatar()
	{
		return $this->morphOne('App\Models\Avatar', 'imageable')->where('type','avatar');
	}
	public function getAvatarsAttribute()
	{
		return $this->avatar->filename;
	}

	public function getTamanhoAttribute(){
		if($this->attributes['size'] == 'micro'){
			return "Muito Pequeno";
		}else if($this->attributes['size'] == 'small'){
			return "Pequeno";
		}else if($this->attributes['size'] == 'medium'){
			return "Médio";
		}else if($this->attributes['size'] == 'big'){
			return "Grande";
		}else if($this->attributes['size'] == 'giant'){
			return "Muito Grande";
		}
	}
	public function getSexoAttribute(){
		if($this->attributes['sex'] == 'male'){
			return "Macho";
		}else {
			return "Fêmea";
		}
	}
	public function getIdadeAttribute(){
		$data = explode("-",$this->birth_date);
		$anoanterior = date('Y')-1;
		$ultimoAniversario = $anoanterior."-".$data[1]."-".$data[2];
		$dataatual = date('Y-m-d');
		$data1 = new \DateTime($ultimoAniversario);
		$data2 = new \DateTime($dataatual);
		$idade = $data1->diff($data2);

		$intervalo = $data1->diff( $data2 );
		if($intervalo->m>=12){
			$anoanterior = date('Y');
			$ultimoAniversario = $anoanterior."-".$aniversario;
			$data1 = new DateTime($ultimoAniversario);
			$intervalo = $data1->diff( $data2 );
			$mes = $intervalo->m;
		}else{
			$mes = $intervalo->m;
		}

		if($idade->y==0){
			return $idade->m." Meses";
		}else if($idade->m > 1){
			if($idade->y>1){
				return $idade->y." Anos e ".$idade->m." Meses";
			}else{
				return $idade->y." Ano e ".$idade->m." Meses";
			}
		}else if($idade->m == 1){
			if($idade->y>1){
				return $idade->y." Anos e ".$idade->m."Mês";
			}else{
				return $idade->y." Ano e ".$idade->m." Mês";
			}
		}else if($idade->y>1){
			return $idade->y." Anos";
		}else{
			return $idade->y." Ano";
		}
	}
	public function owner(){
		return $this->belongsTo('App\Models\User', 'owner_id');
	}
	public function pictures()
	{
		return $this->morphMany('App\Models\Picture', 'imageable')->where('type','picture');
	}
}

resources/views/adopter/index.blade.php
@extends('layouts.app', ['title' => __($title)])


@section('content')
@include('profile.partials.header', [
'title' => __($title),
'class' => 'col-lg-12'
])
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow border-0">
                <div class="card-header bg-secondary border-0">

                    <form method="get" action="{{ route('adopter.search') }}" autocomplete="off" >
                        @csrf
                        <div class="row align-items-center">
                            <div class="col-md-5{{ $errors->has('type_id') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-3">
                                    <select id="filterType" name="type_id" class="dynamic form-control" data-endpoint="api/type" data-labelfield="name" data-valuefield="id" data-current="{{ $type_id ?? old('type_id') }}" data-targetid="filterBreed" data-updateeventtype="updateBreedSelect">
                                        <option value="">Selecione um Tipo</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-5{{ $errors->has('breed_id') ? ' has-danger' : '' }}">
                                <div class="input-group input-group-alternative mb-3">
                                    @if(isset($type_id))
                                    <select id="filterBreed" name="breed_id" class="dynamic form-control" data-endpoint="{{ $type_id?"api/breed/{$type_id}":"" }}" data-labelfield="name" data-valuefield="id" data-current="{{ $breed_id ?? old('breed_id')  }}">
                                        @else
                                        <select id="filterBreed" name="breed_id" class="dynamic form-control" data-labelfield="name" data-valuefield="id" data-current="{{ $breed_id ?? old('breed_id') }}">
                                            @endif
                                            <option value="">Selecione uma raça</option>
                                        </select>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-2 text-center">
                                <button type="submit" class="btn btn-primary mb-3">{{ __('Pesquisar') }}</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
            <div class="form-group row justify-content-center" style="margin-top: 20px">
                <?php $i=1 ?>
                <?php for ($j=0; $j<sizeof($animals);$j++) { ?>
                    @if($animals[$j]->adoption)
                    <div class="col-md-4"> 
                        <div class="form-group text-center bg-gradient-default ">
                            <div class="fusion-image-hovers" style="padding-top: 1.25rem;">
                                @if($animals[$j]->avatar)
                                <div class="form-group bg-background-animals rounded-circle hover-type-liftup  justify-content-center" style="background: url('/storage/animal/featured/{{$animals[$j]->id}}/{{$animals[$j]->avatars}}')">
                                </div>
                                @else
                                <div class="form-group bg-background-animals rounded-circle hover-type-liftup  justify-content-center" style="background: url('/animals/avatar.png')">
                                </div>
                                @endif
                            </div>
                            <div class="card-header bg-transparent">
                                <div class="form-group">
                                    <h2 class="text-center text-white">{{$animals[$j]->name}}</h2>
                                    <h4 class="text-center text-white">{{$animals[$j]->sexo}}</h4>
                                    <a class="btn btn-primary" href="{{ route('animal.show', ['id'=>$animals[$j]->id, 'name'=>$animals[$j]->name]) }}">Visualizar animal</a>

                                </div>
                            </div>
                        </div>
                    </div>
                    <?php if($i%3==0) { ?> 
                    </div>
                    <div class="form-group row">
                    <?php } $i++; ?>
                    @endif
                <?php } ?>

            </div>

        </div>
    </div>


    @include('layouts.footers.auth')
</div>
@push('js')

<script src="/js/poly.js" type="text/javascript" charset="utf-8"></script>
<script src="/js/vendor.js" type="text/javascript" charset="utf-8"></script>
<script src="/js/main.js" type="text/javascript" charset="utf-8"></script>
<script src="/js/jquery.mask.js" type="text/javascript" charset="utf-8"></script>
@endpush
@endsection